# Generated by Django 5.2 on 2025-04-12 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Сообщение об ошибке'), ('suggestion', 'Предложение по улучшению'), ('question', 'Вопрос'), ('other', 'Другое')], default='suggestion', max_length=20, verbose_name='Тип обращения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для ответа')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Сообщение должно содержать минимум 10 символов')], verbose_name='Сообщение')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
    ]
